<a href="https://colab.research.google.com/github/joycenobre-tech/Repositorio_aulas_turma-1715/blob/main/aprendendo_aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lista = [1,2,2,34]
lista.append('show')
print(lista)

[1, 2, 2, 34, 'show']


In [ ]:
for coisa in lista:
  print(coisa)

1
2
2
34
show


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for letra in 'arara':
  print(letra)

a
r
a
r
a


In [ ]:
import numpy as np

lista=[1,2,3,4,5,6,7]

vetor=np.array(lista)

print('print da lista:',lista)
print('print do array:',vetor)

print(type(vetor))
vetor



print da lista: [1, 2, 3, 4, 5, 6, 7]
print do array: [1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr_zeros=np.zeros(10)
arr_ones=np.ones(5)
print(arr_ones)
print(arr_zeros)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr_sequencia=np.arange(10)+5

print(arr_sequencia)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr_sequencia2=np.arange(5,10)
print(arr_sequencia2)

[5 6 7 8 9]


In [ ]:
lista=list(range(5,10))
print(lista)

[5, 6, 7, 8, 9]


In [ ]:
passo=np.arange(0,10,0.2)
print(passo)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [ ]:
array=np.arange(1,20,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
linspace=np.linspace(0,1,100)
linspace

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [8]:
import random
random_randit=random.randint(1,10)
random_randit

6

In [7]:
import numpy as np

np.random.seed(10)

arr_random=np.random.rand(10)
print(arr_random)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]


In [11]:
arr_normal=np.random.normal(0,1,10)
print(arr_normal)

[ 0.09914922  1.39799638 -0.27124799  0.61320418 -0.26731719 -0.54930901
  0.1327083  -0.47614201  1.30847308  0.19501328]


In [12]:
arr_inteiros=np.random.randint(0,100,20)
print(arr_inteiros)

[88 44  5  4 71 88 88 50 54 34 15 77 88 15  6 85 22 11 12 92]


In [13]:
matriz=np.array([[0,1,2,3],[0,1,4,9],[0,1,8,27]])
print(matriz)

[[ 0  1  2  3]
 [ 0  1  4  9]
 [ 0  1  8 27]]


In [14]:
m1=np.zeros((5,3))
print(m1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
m_ones=np.ones((6,10))
print(m_ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
identidade=np.identity(4)
print(identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
array=np.linspace(0,2,30)
print('Array:',array)
print('\n')
print('Mostrando os atributos do array:')
print('\n')
print('ndim= ',array.ndim)
print('shape= ',array.shape)
print('size= ',array.size)
print('dtype= ',array.dtype)
print('itemsize= ',array.itemsize)
print('data= ',array.data)
print('\n')

Array: [0.         0.06896552 0.13793103 0.20689655 0.27586207 0.34482759
 0.4137931  0.48275862 0.55172414 0.62068966 0.68965517 0.75862069
 0.82758621 0.89655172 0.96551724 1.03448276 1.10344828 1.17241379
 1.24137931 1.31034483 1.37931034 1.44827586 1.51724138 1.5862069
 1.65517241 1.72413793 1.79310345 1.86206897 1.93103448 2.        ]


Mostrando os atributos do array:


ndim=  1
shape=  (30,)
size=  30
dtype=  float64
itemsize=  8
data=  <memory at 0x7878f9884e80>




In [19]:
array=np.arange(7,18,1)
print('array: ',array)

print("Elemento na posição 0 do array: ",array[0])
print("Elemento na posição 5 do array: ",array[5])
print("Elemento na última posição do array: ",array[-1])
print("Elemento na posição 4 a partir do último elemento do array: ",array[-4])

array:  [ 7  8  9 10 11 12 13 14 15 16 17]
Elemento na posição 0 do array:  7
Elemento na posição 5 do array:  12
Elemento na última posição do array:  17
Elemento na posição 4 a partir do último elemento do array:  14


In [20]:
array=np.arange(4,20,2)
print('Array original: ',array)
print('Soma 2 no array: ',array+2)
print('Subtrai 2 no array: ',array-2)
print('Multiplica por 3 o array: ',array*3)
print('Divide por 2 o array: ',array/2)
print('Eleva a potência de 2 no array: ',array**2)
print('Divisão inteira por 2 no array: ',array//2)
print('Resto da divisão por 2 no array: ',array%2)
print('Inverso dos elementos do array: ',1/array)

Array original:  [ 4  6  8 10 12 14 16 18]
Soma 2 no array:  [ 6  8 10 12 14 16 18 20]
Subtrai 2 no array:  [ 2  4  6  8 10 12 14 16]
Multiplica por 3 o array:  [12 18 24 30 36 42 48 54]
Divide por 2 o array:  [2. 3. 4. 5. 6. 7. 8. 9.]
Eleva a potência de 2 no array:  [ 16  36  64 100 144 196 256 324]
Divisão inteira por 2 no array:  [2 3 4 5 6 7 8 9]
Resto da divisão por 2 no array:  [0 0 0 0 0 0 0 0]
Inverso dos elementos do array:  [0.25       0.16666667 0.125      0.1        0.08333333 0.07142857
 0.0625     0.05555556]


In [23]:
arr1=np.arange(9)
arr2=arr1.reshape((3,3))
print(arr1)
print(arr2)
arr3=arr2.ravel()
print('array3: ',arr3)
arr4=arr2.flatten()
print('Array após flatten: ',arr4)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
array3:  [0 1 2 3 4 5 6 7 8]
Array após flatten:  [0 1 2 3 4 5 6 7 8]


In [29]:
import numpy as np
import random
np.random.seed(42)
array=np.random.randint(0,100,10)
print('Array: ',array)
print('Maior valor do array: ',array.max())
print('Posição do maior valor do array: ',array.argmax())
print('Menor valor do array: ',array.min())
print('Posição do menor valor do array: ',array.argmin())
print('Soma dos elementos: ',array.sum())
print('Média dos valores: ',array.mean())
print('Desvio padrão dos elementos: ',array.std())


Array:  [51 92 14 71 60 20 82 86 74 74]
Maior valor do array:  92
Posição do maior valor do array:  1
Menor valor do array:  14
Posição do menor valor do array:  2
Soma dos elementos:  624
Média dos valores:  62.4
Desvio padrão dos elementos:  25.370061095708856


In [30]:
indices=np.argsort(array)
print('Array: ',array)
print('Indices: ',indices)

Array:  [51 92 14 71 60 20 82 86 74 74]
Indices:  [2 5 0 4 3 8 9 6 7 1]


In [35]:
array.sort()
print('Array ordenado: ',array[::-1])
print('Array ordenado: ',array[0::])
print('Muda para string: ',array.astype(str))

Array ordenado:  [92 86 82 74 74 71 60 51 20 14]
Array ordenado:  [14 20 51 60 71 74 74 82 86 92]
Muda para string:  ['14' '20' '51' '60' '71' '74' '74' '82' '86' '92']


In [36]:
array=np.arange(18).reshape((3,6))
print('Matriz:')
print(array)

Matriz:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [37]:
mascara = array>7
mascara

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [38]:
array[mascara]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [39]:
mask = (array>7)
print('Máscara booleana da matriz para valores maiores que 7')
print(mask)
print('\nRecuperando apenas os elementos maiores que 7:')
print(array[mask])
print('\nModificando os elementos maiores que 7:')
array[mask]=0
print(array)

Máscara booleana da matriz para valores maiores que 7
[[False False False False False False]
 [False False  True  True  True  True]
 [ True  True  True  True  True  True]]

Recuperando apenas os elementos maiores que 7:
[ 8  9 10 11 12 13 14 15 16 17]

Modificando os elementos maiores que 7:
[[0 1 2 3 4 5]
 [6 7 0 0 0 0]
 [0 0 0 0 0 0]]


In [40]:
import numpy as np
import random
np.random.seed(42)
aleat_int=np.random.randint(0,100,20)
print(aleat_int)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]


In [41]:
pares=aleat_int%2==0
print(pares)

[False  True  True False  True  True  True  True  True  True False False
 False  True False  True False False False False]


In [42]:
aleat_int[pares]

array([92, 14, 60, 20, 82, 86, 74, 74,  2, 52])

In [43]:
aleat_int[~pares]=0
aleat_int

array([ 0, 92, 14,  0, 60, 20, 82, 86, 74, 74,  0,  0,  0,  2,  0, 52,  0,
        0,  0,  0])

In [44]:
maiores_50=aleat_int>50
print(maiores_50)

[False  True False False  True False  True  True  True  True False False
 False False False  True False False False False]


In [45]:
print(pares&maiores_50)

[False  True False False  True False  True  True  True  True False False
 False False False  True False False False False]


In [46]:
print(aleat_int[pares&maiores_50])

[92 60 82 86 74 74 52]


In [48]:
print(aleat_int[(aleat_int%2==0)&(aleat_int>50)])

[92 60 82 86 74 74 52]


In [49]:
print(aleat_int[(aleat_int%2==0)|(aleat_int>50)])

[ 0 92 14  0 60 20 82 86 74 74  0  0  0  2  0 52  0  0  0  0]


Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um numpy array bidimensional (matriz) com 4 linhas e 5 colunas.

In [4]:
lista = list(range(0, 20))
print(lista)

import numpy as np
matriz =np.array(lista).reshape(4,5)
print(matriz)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz A com 5 linhas e 6 colunas.

In [9]:
import numpy as np

# Array unidimensional com 30 números aleatórios entre 0 e 20

array = np.random.randint(0, 21, 30)
print("Array:")
print(array)
# Transformando em matriz 5x6
A = array.reshape(5, 6)
print("\nMatriz A:")
print(A)

Array:
[19  4  4  1 18 18  8 10 17  6 12 18  1 12 18 10 13 12 18 20  8  8 17 14
 16 13  0  5 19  1]

Matriz A:
[[19  4  4  1 18 18]
 [ 8 10 17  6 12 18]
 [ 1 12 18 10 13 12]
 [18 20  8  8 17 14]
 [16 13  0  5 19  1]]


Exercício 3)
Crie uma view da matriz A gerada na célula anterior contendo:

as linhas de A com índices 0,1 e 3
as linhas de A com índice 1 e 2 e as colunas com índice 0,2 e 4
as linhas de A com índice 1 e 3 e as colunas com índice 1 e 3

In [10]:
view1 = A[[0, 1, 3], :]
print(view1)

[[19  4  4  1 18 18]
 [ 8 10 17  6 12 18]
 [18 20  8  8 17 14]]


In [11]:
view2 = A[np.ix_([1, 2], [0, 2, 4])]
print(view2)

[[ 8 17 12]
 [ 1 18 13]]


In [12]:
view3 = A[np.ix_([1, 3], [1,3])]
print(view3)

[[10  6]
 [20  8]]


Exercício 4)
Construa um array A bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.

faça uma cópia do array A criado, chamando a cópia de Ac
Substitua todos os elementos do array A que sejam maiores que 10 pelo valor -1
Substitua todos os elementos do array Ac que sejam maiores que 7 e menores que 15 pelo valor -1
Dica: Gere máscaras booleanas para realizar as modificações nos arrays.

In [14]:
import numpy as np
# Criando a matriz A (5x6) com valores aleatórios entre 0 e 20
A = np.random.randint(0, 21, (5, 6))
print("Matriz A original:")
print(A)
# Criando uma cópia de A
Ac = A.copy()
# Substituindo em A os valores maiores que 10 por -1
A[A > 10] = -1
# Substituindo em Ac os valores maiores que 7 e menores que 15 por -1
Ac[(Ac > 7) & (Ac < 15)] = -1
print("\nMatriz A modificada:")
print(A)
print("\nMatriz Ac modificada:")
print(Ac)

Matriz A original:
[[15  0  5  8 11  2]
 [ 0  6  6 19 10 18]
 [ 1 17 13 14 12 17]
 [13 20  7 10  9  6]
 [19 16  2 10 20 14]]

Matriz A modificada:
[[-1  0  5  8 -1  2]
 [ 0  6  6 -1 10 -1]
 [ 1 -1 -1 -1 -1 -1]
 [-1 -1  7 10  9  6]
 [-1 -1  2 10 -1 -1]]

Matriz Ac modificada:
[[15  0  5 -1 -1  2]
 [ 0  6  6 19 -1 18]
 [ 1 17 -1 -1 -1 17]
 [-1 20  7 -1 -1  6]
 [19 16  2 -1 20 -1]]


Exercício 5)
Construa um array A com 20 linhas e 10 colunas onde os elementos são os números interios de 1 até 200.

Crie uma view de A chamada A_lpares contendo apenas as linhas de A com índice par.
Crie uma view de A chamada A_lpares_cimpares contendo as linhas A com índice par e colunas com índice ímpar.

Dica: Construa uma máscara booleana

In [18]:
import numpy as np
# Criando a matriz A (20x10) com valores inteiros aleatórios entre 1 e 200
A = np.random.randint(1, 201, (20, 10))
print("Matriz A original:")
print(A)

# Máscara para linhas com índice par
linhas_pares = np.arange(A.shape[0]) % 2 == 0
# View com linhas de índice par
A_lpares = A[linhas_pares, :]
print("\nA_lpares:")
print(A_lpares)
# Máscara para colunas com índice ímpar
colunas_impares = np.arange(A.shape[1]) % 2 == 1
# View com linhas pares e colunas ímpares
A_lpares_cimpares = A[linhas_pares][:, colunas_impares]
print("\nA_lpares_cimpares:")
print(A_lpares_cimpares)

Matriz A original:
[[  3 156  22  13   1  17  47  80 140 102]
 [ 43  78  51 173  47 135  77 200 179 115]
 [ 59 107 176 133  77  99 110 146 115 173]
 [192  75  74  97  59  73  69 175 191  16]
 [ 43 124 131  66  77   1   3 102 186 165]
 [144  10 161 125  62 155  34 161  44   6]
 [ 13 188 104 195   9 111  86  13 138  64]
 [ 39  28  94  11 131  12 164  66  34 112]
 [121  62 120 138  70  74  50 164 145  73]
 [158 129  10  36 141 170 154 148 137  53]
 [ 94 146 174  53 191 165 131 144  42 192]
 [  2  22 160 147  69 150 177 188 135  47]
 [164  61 175  79  20  43  94  58   4  24]
 [142 152  57  71 174 106  34 200 154  44]
 [ 32 173 134 175  69  74  62  68 193  20]
 [186  14 193 127 111  81  28  84 122  74]
 [188 192 184  72 160  66 183  99 138 180]
 [179 119 144 126  93  88 160  24 164 132]
 [123   3  75  61 175  48 116  55 105  23]
 [140  84  74 199 108   4  19 110 113 195]]

A_lpares:
[[  3 156  22  13   1  17  47  80 140 102]
 [ 59 107 176 133  77  99 110 146 115 173]
 [ 43 124 131  66  77  

Exercício 6)
Substitua os elememtos do array A do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

Dica: Construa uma máscara booleana

In [19]:
import numpy as np
# Matriz A com números de 1 a 200
A = np.arange(1, 201).reshape(20, 10)
# Índices das linhas e colunas
linhas = np.arange(A.shape[0]).reshape(-1, 1)
colunas = np.arange(A.shape[1]).reshape(1, -1)
# Máscara: linha par OU coluna par
mascara = (linhas % 2 == 0) | (colunas % 2 == 0)
# Substitui por -1 onde a máscara é True
A[mascara] = -1
print(A)

[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  12  -1  14  -1  16  -1  18  -1  20]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  32  -1  34  -1  36  -1  38  -1  40]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  52  -1  54  -1  56  -1  58  -1  60]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  72  -1  74  -1  76  -1  78  -1  80]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  92  -1  94  -1  96  -1  98  -1 100]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 112  -1 114  -1 116  -1 118  -1 120]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 132  -1 134  -1 136  -1 138  -1 140]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1 154  -1 156  -1 158  -1 160]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 172  -1 174  -1 176  -1 178  -1 180]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 192  -1 194  -1 196  -1 198  -1 200]]


Exercício 7)
Construa uma função chamada ordena_linhas que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:

A = np.array([[20, 26, 12],
              [8, 3, 26],
              [3, 10, 4]])
print(ordena_linhas(A))
deve resultar em

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]

In [20]:
import numpy as np
def ordena_linhas(A):
  return A[np.argsort(A[:, 0])]
# Exemplo
A = np.array([[20, 26, 12],
[8, 3, 26],
[3, 10, 4]])
print(ordena_linhas(A))

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
